name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build Docker Image
        uses: docker/build-push-action@master
        with:
          context: .
          file: 'Dockerfile'
